# Generated by Django 2.2 on 2020-03-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CronaVirus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='cities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CronaVirus.Cities'),
        ),
    ]
