# Generated by Django 2.2 on 2020-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CronaVirus', '0002_auto_20200302_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='confirmCount',
            field=models.BigIntegerField(blank=True, help_text='Number of confirmed patients ', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='curedCount',
            field=models.BigIntegerField(blank=True, help_text='Number of cured patients ', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='currentConfirmedCount',
            field=models.BigIntegerField(blank=True, help_text='Number of current remaining confirmed patients ', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='deadCount',
            field=models.BigIntegerField(blank=True, help_text='Number of dead patients ', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='locationId',
            field=models.BigIntegerField(blank=True, help_text='ID of cities In mainland China, the locationId is zip code, Outsides mainland China, the explanation of locationId is not sure ', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='suspectedCount',
            field=models.BigIntegerField(blank=True, help_text='Number of suspected patients ', null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='updateTime',
            field=models.BigIntegerField(blank=True, help_text='The latest updated time', null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='confirmCount',
            field=models.BigIntegerField(blank=True, help_text='Number of confirmed patients ', null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='curedCount',
            field=models.BigIntegerField(blank=True, help_text='Number of cured patients ', null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='currentConfirmedCount',
            field=models.BigIntegerField(blank=True, help_text='Number of current remaining confirmed patients ', null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='deadCount',
            field=models.BigIntegerField(blank=True, help_text='Number of dead patients ', null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='locationId',
            field=models.BigIntegerField(blank=True, help_text='ID of cities In mainland China, the locationId is zip code, Outsides mainland China, the explanation of locationId is not sure ', null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='suspectedCount',
            field=models.BigIntegerField(blank=True, help_text='Number of suspected patients ', null=True),
        ),
        migrations.AlterField(
            model_name='cronavirus',
            name='updateTime',
            field=models.BigIntegerField(blank=True, help_text='The latest updated time', null=True),
        ),
    ]
