# Generated by Django 2.2 on 2020-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CronaVirus', '0003_auto_20200302_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='Title of the news', max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('infosource', models.URLField(blank=True, help_text='Source Info', max_length=255, null=True)),
                ('pubdate', models.BigIntegerField(blank=True, help_text='Publish date ', null=True)),
                ('provinceName', models.CharField(blank=True, help_text='Proviance Name', max_length=255, null=True)),
                ('provinceId', models.IntegerField(blank=True, help_text='ProvianceId ', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('_id', models.IntegerField(blank=True, help_text='News Id ', null=True)),
                ('title', models.CharField(blank=True, help_text='Title of the news', max_length=255, null=True)),
                ('mainSummary', models.CharField(blank=True, help_text='Main Summary of the news', max_length=255, null=True)),
                ('body', models.TextField(blank=True, help_text='The reality', null=True)),
                ('infosource', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
